### Impor modules

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, Dense
from tensorflow.keras.models import Model

### Toy data generation

In [3]:
# Sample input data (a list of sentences, where each sentence is a list of word indices)
data = np.array([[3, 6, 9], [2, 5, 8], [1, 4, 7]])

# Hyperparameters
vocab_size = 10  # Vocabulary size (number of unique words in your dataset)
embedding_dim = 4  # Size of the embedding vectors
input_length = 3 # Length of the input 

In [4]:
# Define the input layer
input_layer = Input(shape=(input_length,), dtype="int32")

# Add the embedding layer
embedding_layer = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=input_length, name='Embedd')(input_layer)

# Create the model
model = Model(inputs=input_layer, outputs=embedding_layer)

# Print the model summary
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
Embedd (Embedding)           (None, 3, 4)              40        
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


### Check whether the size of second dimension of the data matches the input length of the model.

In [5]:
data.shape[1] == model.input[1].shape[0]

True

### Return the embedding vectors
#### (batch, input_lenght, embedding_dim)

In [6]:
model(data)

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[ 0.00090636, -0.04525907,  0.01140468, -0.00727352],
        [ 0.01679579, -0.03768013,  0.01675231, -0.03288104],
        [ 0.02741626,  0.00246184, -0.04513309,  0.03628683]],

       [[ 0.03387538,  0.03149626, -0.00531118, -0.04352448],
        [ 0.0344721 ,  0.03498758, -0.01548102, -0.02356925],
        [-0.00263525,  0.04107567,  0.00939419, -0.04705123]],

       [[-0.03991412, -0.02816613, -0.00644202,  0.03202518],
        [-0.03499562,  0.04683853,  0.03016383,  0.01458838],
        [ 0.04784336, -0.04316411, -0.01562294, -0.02190723]]],
      dtype=float32)>

### Access the embedding results for each word using tf.nn.embedding_lookup

In [7]:
word_idx = 0
tf.nn.embedding_lookup(model.get_layer('Embedd').weights, word_idx)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.00134405,  0.00113857,  0.01210244, -0.04505004], dtype=float32)>