In [2]:
import numpy as np

###  MLP Mechanism
#### Toyset generation

In [6]:
DM = np.array([[56,181],[33,168],[61,170]])
WMt = np.array([[0.5], [-0.2]])
bias = 9.5

In [8]:
DM.shape, WMt.shape

((3, 2), (2, 1))

#### Operation

In [11]:
def sigmoid(x):
    return np.round(1/(1 + np.exp(-x)), 3)

DM_WMt = np.matmul(DM, WMt)
print(DM_WMt)
y_star = DM_WMt+bias
print(y_star)

sigmoid(y_star)


[[ -8.2]
 [-17.1]
 [ -3.5]]
[[ 1.3]
 [-7.6]
 [ 6. ]]


array([[0.786],
       [0.001],
       [0.998]])