In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.layers import LSTM, Input, TimeDistributed, RepeatVector, SimpleRNN, Dense
from tensorflow.keras import Model

### Return_sequences = True

In [2]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=True)(InpL)
LSTML

<KerasTensor: shape=(None, 20, 10) dtype=float32 (created by layer 'lstm')>

### Return_sequences = False

In [3]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=False)(InpL)
LSTML

<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_1')>

### Return_sequences = True & return_state =True

In [4]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=True, return_state =True)(InpL)
model = Model(InpL, LSTML)
LSTML

[<KerasTensor: shape=(None, 20, 10) dtype=float32 (created by layer 'lstm_2')>,
 <KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_2')>,
 <KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_2')>]

In [5]:
Dataset = np.random.rand(TimeStep * VarSize).reshape(1, TimeStep, VarSize)
lstm1, state_h, state_c =model.predict(Dataset)
lstm1, state_h, state_c

(array([[[-0.04156275,  0.08001338,  0.03562296,  0.22103539,
          -0.14513186, -0.00602775,  0.03863269, -0.09025482,
          -0.04184421,  0.06167698],
         [-0.04277663,  0.2883625 ,  0.12028064,  0.39339787,
          -0.30404112,  0.02212961,  0.09520419, -0.14840594,
          -0.11289477, -0.05737477],
         [-0.01246768,  0.19644254,  0.18030156,  0.46179917,
          -0.25489995,  0.02557311,  0.11631395, -0.26698187,
          -0.13034704, -0.03120573],
         [ 0.04067663,  0.24112576,  0.21133985,  0.4543307 ,
          -0.19860333,  0.01216052, -0.007397  , -0.26433727,
          -0.15450701,  0.04804842],
         [ 0.01089755,  0.3017028 ,  0.17517112,  0.55459595,
          -0.21754877, -0.02841754, -0.01016164, -0.10727151,
          -0.25296578,  0.17465037],
         [ 0.03365986,  0.23787202,  0.15470678,  0.6021135 ,
          -0.21627575, -0.10512099,  0.1318622 , -0.15622057,
          -0.23499453,  0.25459522],
         [ 0.00195617,  0.25638083

#### The last lstm output and hidden state values are same

In [6]:
lstm1[0, -1], state_h

(array([ 0.01197781,  0.34264514,  0.2614726 ,  0.55744207, -0.263543  ,
        -0.28072345,  0.22432303, -0.07853606, -0.1604498 ,  0.1685156 ],
       dtype=float32),
 array([[ 0.01197781,  0.34264514,  0.2614726 ,  0.55744207, -0.263543  ,
         -0.28072345,  0.22432303, -0.07853606, -0.1604498 ,  0.1685156 ]],
       dtype=float32))

### Return_sequences = False & return_state =True

In [7]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=False, return_state =True)(InpL)
model = Model(InpL, LSTML)

In [8]:
Dataset = np.random.rand(TimeStep * VarSize).reshape(1, TimeStep, VarSize)
lstm1, state_h, state_c =model.predict(Dataset)
lstm1, state_h, state_c

(array([[ 0.22038084,  0.18965082,  0.5009733 , -0.25353464,  0.21773149,
         -0.4413395 ,  0.51663595,  0.5425975 ,  0.28696233,  0.10665391]],
       dtype=float32),
 array([[ 0.22038084,  0.18965082,  0.5009733 , -0.25353464,  0.21773149,
         -0.4413395 ,  0.51663595,  0.5425975 ,  0.28696233,  0.10665391]],
       dtype=float32),
 array([[ 0.39819732,  1.3813059 ,  1.1038511 , -0.7830069 ,  0.46367028,
         -0.63205224,  1.2784318 ,  1.2787627 ,  0.60210246,  0.2274644 ]],
       dtype=float32))

In [9]:
LSTML

[<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_3')>,
 <KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_3')>,
 <KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_3')>]

### Stacked LSTM models

In [10]:
InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=True)(InpL)
LSTML = LSTM(Units, return_sequences=False)(LSTML)
model = Model(InpL, LSTML)
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 20, 30)]          0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 20, 10)            1640      
_________________________________________________________________
lstm_5 (LSTM)                (None, 10)                840       
Total params: 2,480
Trainable params: 2,480
Non-trainable params: 0
_________________________________________________________________


### M to N LSTM

In [11]:
InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=False)(InpL)

LSTMRepeat = RepeatVector(Units)(LSTML)
LSTML = TimeDistributed(Dense(10))(LSTMRepeat)
Output = LSTM(1, return_sequences=False)(LSTML)
model = Model(InpL, LSTMRepeat)
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 20, 30)]          0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 10)                1640      
_________________________________________________________________
repeat_vector (RepeatVector) (None, 10, 10)            0         
Total params: 1,640
Trainable params: 1,640
Non-trainable params: 0
_________________________________________________________________


#### Check repeat vector

In [12]:
model.predict(Dataset)

array([[[-0.37059438,  0.34338307, -0.27796715,  0.23656084,
         -0.18221886, -0.51808023, -0.42632604,  0.49360415,
         -0.22799839,  0.43260345],
        [-0.37059438,  0.34338307, -0.27796715,  0.23656084,
         -0.18221886, -0.51808023, -0.42632604,  0.49360415,
         -0.22799839,  0.43260345],
        [-0.37059438,  0.34338307, -0.27796715,  0.23656084,
         -0.18221886, -0.51808023, -0.42632604,  0.49360415,
         -0.22799839,  0.43260345],
        [-0.37059438,  0.34338307, -0.27796715,  0.23656084,
         -0.18221886, -0.51808023, -0.42632604,  0.49360415,
         -0.22799839,  0.43260345],
        [-0.37059438,  0.34338307, -0.27796715,  0.23656084,
         -0.18221886, -0.51808023, -0.42632604,  0.49360415,
         -0.22799839,  0.43260345],
        [-0.37059438,  0.34338307, -0.27796715,  0.23656084,
         -0.18221886, -0.51808023, -0.42632604,  0.49360415,
         -0.22799839,  0.43260345],
        [-0.37059438,  0.34338307, -0.27796715,  0.2