In [38]:
import numpy as np
import pandas as pd
from tensorflow.keras.layers import LSTM, Input, TimeDistributed, RepeatVector, SimpleRNN
from tensorflow.keras import Model, regularizers

### Return_sequences = True

In [30]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=True)(InpL)
LSTML

<KerasTensor: shape=(None, 20, 10) dtype=float32 (created by layer 'lstm_9')>

### Return_sequences = False

In [31]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=False)(InpL)
LSTML

<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_10')>

### Return_sequences = True & return_state =True

In [42]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=True, return_state =True)(InpL)
model = Model(InpL, LSTML)
LSTML

[<KerasTensor: shape=(None, 20, 10) dtype=float32 (created by layer 'lstm_14')>,
 <KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_14')>,
 <KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_14')>]

In [51]:
Dataset = np.random.rand(TimeStep * VarSize).reshape(1, TimeStep, VarSize)
lstm1, state_h, state_c =model.predict(Dataset)
lstm1, state_h, state_c

(array([[[ 0.10418471, -0.10299467, -0.03308957, -0.12693873,
           0.06858419, -0.05860742, -0.1285915 ,  0.11070773,
          -0.01663681,  0.06277633],
         [ 0.18883878, -0.28232977, -0.13730997, -0.10400794,
           0.08172072, -0.08473852, -0.36194646,  0.01631832,
           0.04124894,  0.16498668],
         [ 0.36693642, -0.3296919 , -0.16808738, -0.10541847,
           0.0902691 , -0.08297814, -0.6160102 ,  0.04428409,
           0.0431894 ,  0.1570348 ],
         [ 0.47693694, -0.4077609 , -0.07768168, -0.06384867,
           0.18653767, -0.09649818, -0.6437236 ,  0.18595375,
          -0.02047893,  0.03371238],
         [ 0.37087005, -0.34538823, -0.05237258, -0.11939853,
           0.20827551, -0.08198439, -0.5756054 ,  0.2753517 ,
          -0.04047269,  0.04319203],
         [ 0.45024145, -0.57471347, -0.11312895, -0.16705999,
           0.1360178 , -0.06367707, -0.66484505,  0.22979371,
           0.03135851,  0.01712436],
         [ 0.48487017, -0.46401256

#### The last lstm output and hidden state values are same

In [52]:
lstm1[0, -1], state_h

(array([ 0.476748  , -0.49156404, -0.14146677, -0.25162914,  0.16426216,
         0.04446121, -0.7061612 ,  0.32513285, -0.08177719, -0.06405693],
       dtype=float32),
 array([[ 0.476748  , -0.49156404, -0.14146677, -0.25162914,  0.16426216,
          0.04446121, -0.7061612 ,  0.32513285, -0.08177719, -0.06405693]],
       dtype=float32))

### Return_sequences = False & return_state =True

In [54]:
TimeStep = 20
VarSize = 30
Units = 10

InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=False, return_state =True)(InpL)
model = Model(InpL, LSTML)

In [55]:
Dataset = np.random.rand(TimeStep * VarSize).reshape(1, TimeStep, VarSize)
lstm1, state_h, state_c =model.predict(Dataset)
lstm1, state_h, state_c

(array([[-0.62462705, -0.28413856,  0.16088091, -0.3796    ,  0.03474068,
          0.03447613, -0.24979752, -0.4051117 , -0.64492005,  0.15125301]],
       dtype=float32),
 array([[-0.62462705, -0.28413856,  0.16088091, -0.3796    ,  0.03474068,
          0.03447613, -0.24979752, -0.4051117 , -0.64492005,  0.15125301]],
       dtype=float32),
 array([[-2.8718817 , -0.5888344 ,  0.49813947, -0.55632097,  0.11454298,
          0.09786666, -0.44266573, -1.4738995 , -1.3949063 ,  0.2852    ]],
       dtype=float32))

In [58]:
LSTML

<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'lstm_16')>

### Stacked LSTM models

In [59]:
InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=True)(InpL)
LSTML = LSTM(Units, return_sequences=False)(LSTML)
model = Model(InpL, LSTML)
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_20 (InputLayer)        [(None, 20, 30)]          0         
_________________________________________________________________
lstm_18 (LSTM)               (None, 20, 10)            1640      
_________________________________________________________________
lstm_19 (LSTM)               (None, 10)                840       
Total params: 2,480
Trainable params: 2,480
Non-trainable params: 0
_________________________________________________________________


### M to N LSTM

In [74]:
InpL = Input(shape=(TimeStep, VarSize))
LSTML = LSTM(Units, return_sequences=False)(InpL)

LSTMRepeat = RepeatVector(Units)(LSTML)
LSTML = TimeDistributed(Dense(10))(LSTMRepeat)
Output = LSTM(1, return_sequences=False)(LSTML)
model = Model(InpL, LSTMRepeat)
model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_30 (InputLayer)        [(None, 20, 30)]          0         
_________________________________________________________________
lstm_34 (LSTM)               (None, 10)                1640      
_________________________________________________________________
repeat_vector_7 (RepeatVecto (None, 10, 10)            0         
Total params: 1,640
Trainable params: 1,640
Non-trainable params: 0
_________________________________________________________________


#### Check repeat vector

In [75]:
model.predict(Dataset)

array([[[-0.07611243,  0.01417255, -0.24152361,  0.1302941 ,
         -0.21031685,  0.5664202 , -0.357486  ,  0.5785637 ,
          0.1046114 ,  0.32735392],
        [-0.07611243,  0.01417255, -0.24152361,  0.1302941 ,
         -0.21031685,  0.5664202 , -0.357486  ,  0.5785637 ,
          0.1046114 ,  0.32735392],
        [-0.07611243,  0.01417255, -0.24152361,  0.1302941 ,
         -0.21031685,  0.5664202 , -0.357486  ,  0.5785637 ,
          0.1046114 ,  0.32735392],
        [-0.07611243,  0.01417255, -0.24152361,  0.1302941 ,
         -0.21031685,  0.5664202 , -0.357486  ,  0.5785637 ,
          0.1046114 ,  0.32735392],
        [-0.07611243,  0.01417255, -0.24152361,  0.1302941 ,
         -0.21031685,  0.5664202 , -0.357486  ,  0.5785637 ,
          0.1046114 ,  0.32735392],
        [-0.07611243,  0.01417255, -0.24152361,  0.1302941 ,
         -0.21031685,  0.5664202 , -0.357486  ,  0.5785637 ,
          0.1046114 ,  0.32735392],
        [-0.07611243,  0.01417255, -0.24152361,  0.1